"""Bible API routes.

Provides endpoints for querying scripture with 4-dimensional responses
(literal, allegorical, moral, anagogical), passage retrieval and
full-text search.
"""

from __future__ import annotations

import logging
from typing import Any

from fastapi import APIRouter, HTTPException, Query, status
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/bible", tags=["Bible"])

# ---------------------------------------------------------------------------
# Request / response models
# ---------------------------------------------------------------------------


class AskRequest(BaseModel):
    """Request body for asking a question about scripture."""

    question: str
    translation: str = "BT"
    include_magisterium: bool = True
    include_patristic: bool = True
    max_passages: int = Field(default=5, ge=1, le=20)


class FourDimensionalResponse(BaseModel):
    """A 4-dimensional scripture response following patristic exegesis.

    The four senses of scripture:
    - Literal (historical): what the text says
    - Allegorical (typological): what the text means for faith
    - Moral (tropological): what the text means for behaviour
    - Anagogical (eschatological): what the text means for ultimate destiny
    """

    question: str
    passages: list[dict[str, Any]] = Field(default_factory=list)
    literal_sense: str = ""
    allegorical_sense: str = ""
    moral_sense: str = ""
    anagogical_sense: str = ""
    magisterium_references: list[dict[str, Any]] = Field(default_factory=list)
    patristic_references: list[dict[str, Any]] = Field(default_factory=list)


class PassageResponse(BaseModel):
    """Response containing a specific scripture passage."""

    book: str
    chapter: int
    verses: list[dict[str, Any]] = Field(default_factory=list)
    translation: str = "BT"
    context: dict[str, Any] = Field(default_factory=dict)


class SearchResultItem(BaseModel):
    """A single scripture search result."""

    reference: str
    content: str
    score: float
    book: str = ""
    chapter: int = 0
    verse: int = 0


class SearchResponse(BaseModel):
    """Response for scripture search queries."""

    query: str
    total_results: int
    results: list[SearchResultItem] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post("/ask", response_model=FourDimensionalResponse)
async def ask_scripture(request: AskRequest) -> FourDimensionalResponse:
    """Ask a question about scripture and receive a 4-dimensional response.

    The response follows the traditional Catholic four senses of
    scripture (literal, allegorical, moral, anagogical) and optionally
    includes Magisterium and patristic references.
    """
    from backend.app.services.rag.rag_service import RAGService

    rag = RAGService()

    # Search biblical collection
    scripture_results = rag.search("biblia_pl", request.question, limit=request.max_passages)

    passages = [
        {
            "content": r.content,
            "score": r.score,
            "metadata": r.metadata,
        }
        for r in scripture_results
    ]

    # Search Magisterium if requested
    magisterium_refs: list[dict[str, Any]] = []
    if request.include_magisterium:
        mag_results = rag.search_magisterium(request.question, limit=3)
        magisterium_refs = [
            {
                "content": r.content,
                "document_title": r.document_title,
                "paragraph": r.paragraph,
                "pope_or_council": r.pope_or_council,
                "score": r.score,
            }
            for r in mag_results
        ]

    # Search patristic if requested
    patristic_refs: list[dict[str, Any]] = []
    if request.include_patristic:
        pat_results = rag.search("patrystyka", request.question, limit=3)
        patristic_refs = [
            {
                "content": r.content,
                "score": r.score,
                "metadata": r.metadata,
            }
            for r in pat_results
        ]

    # Build 4-dimensional response
    # In production this would be generated by an LLM with the retrieved
    # context.  Here we provide structured placeholders.
    combined_text = " ".join(r.content for r in scripture_results[:3])

    return FourDimensionalResponse(
        question=request.question,
        passages=passages,
        literal_sense=_generate_literal_sense(request.question, combined_text),
        allegorical_sense=_generate_allegorical_sense(request.question, combined_text),
        moral_sense=_generate_moral_sense(request.question, combined_text),
        anagogical_sense=_generate_anagogical_sense(request.question, combined_text),
        magisterium_references=magisterium_refs,
        patristic_references=patristic_refs,
    )


@router.get("/passage/{book}/{chapter}", response_model=PassageResponse)
async def get_passage(
    book: str,
    chapter: int,
    verse_start: int | None = Query(default=None, description="Starting verse"),
    verse_end: int | None = Query(default=None, description="Ending verse"),
    translation: str = Query(default="BT", description="Bible translation code"),
) -> PassageResponse:
    """Retrieve a specific scripture passage by book and chapter.

    Optionally filter by verse range.
    """
    from backend.app.services.rag.rag_service import RAGService

    rag = RAGService()

    query = f"{book} {chapter}"
    if verse_start:
        query += f",{verse_start}"
        if verse_end:
            query += f"-{verse_end}"

    results = rag.search_scripture(query, limit=20)

    verses = []
    for r in results:
        if r.book.lower() == book.lower() and r.chapter == chapter:
            if verse_start and r.verse < verse_start:
                continue
            if verse_end and r.verse > verse_end:
                continue
            verses.append({
                "verse": r.verse,
                "content": r.content,
                "translation": r.translation,
            })

    verses.sort(key=lambda v: v["verse"])

    return PassageResponse(
        book=book,
        chapter=chapter,
        verses=verses,
        translation=translation,
        context={
            "total_verses_found": len(verses),
            "verse_range": f"{verse_start or 1}-{verse_end or 'end'}",
        },
    )


@router.get("/search", response_model=SearchResponse)
async def search_scripture(
    q: str = Query(..., description="Search query", min_length=1),
    limit: int = Query(default=10, ge=1, le=50, description="Max results"),
    book: str | None = Query(default=None, description="Filter by book"),
) -> SearchResponse:
    """Full-text semantic search across scripture."""
    from backend.app.services.rag.rag_service import RAGService

    rag = RAGService()

    emotion_filter: dict[str, Any] | None = None
    if book:
        emotion_filter = {"book": book}

    results = rag.search_scripture(q, emotion_filter=emotion_filter, limit=limit)

    items = [
        SearchResultItem(
            reference=f"{r.book} {r.chapter},{r.verse}",
            content=r.content,
            score=r.score,
            book=r.book,
            chapter=r.chapter,
            verse=r.verse,
        )
        for r in results
    ]

    return SearchResponse(
        query=q,
        total_results=len(items),
        results=items,
    )


# ---------------------------------------------------------------------------
# Helpers for 4-dimensional response generation
# ---------------------------------------------------------------------------


def _generate_literal_sense(question: str, context: str) -> str:
    """Generate the literal/historical sense.

    In production, this would call an LLM with the retrieved context.
    """
    if not context:
        return "Brak wystarczajacego kontekstu dla interpretacji literalnej."
    return (
        f"Sens literalny: Na podstawie znalezionych fragmentow, "
        f"tekst odnosi sie bezposrednio do pytania: '{question}'. "
        f"Historyczny kontekst wymaga dalszej analizy."
    )


def _generate_allegorical_sense(question: str, context: str) -> str:
    """Generate the allegorical/typological sense."""
    if not context:
        return "Brak wystarczajacego kontekstu dla interpretacji alegorycznej."
    return (
        f"Sens alegoryczny: Fragment ten moze byc odczytany jako typ "
        f"lub figura wskazujaca na Chrystusa i Kosciol."
    )


def _generate_moral_sense(question: str, context: str) -> str:
    """Generate the moral/tropological sense."""
    if not context:
        return "Brak wystarczajacego kontekstu dla interpretacji moralnej."
    return (
        f"Sens moralny: Tekst wzywa do konkretnej odpowiedzi zyciowej, "
        f"do nawrocenia i przemiany serca."
    )


def _generate_anagogical_sense(question: str, context: str) -> str:
    """Generate the anagogical/eschatological sense."""
    if not context:
        return "Brak wystarczajacego kontekstu dla interpretacji anagogicznej."
    return (
        f"Sens anagogiczny: Fragment wskazuje na rzeczywistosc eschatologiczna, "
        f"na pelnie zbawienia i zycie wieczne."
    )
